
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: greycat
  namespace: wattopus
  labels: { app: greycat }
spec:
  serviceName: greycat
  replicas: 1
  selector:
    matchLabels: { app: greycat }
  template:
    metadata:
      labels: { app: greycat }
    spec:
      enableServiceLinks: false
      containers:
        - name: greycat
          image: inkedstinct/greycat-twin:0.1
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          volumeMounts:
            - { name: data, mountPath: /app/gcdata, subPath: gcdata } 
            - { name: data, mountPath: /app/backup, subPath: backup }  # Backup snapshots
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests: { storage: 1Gi }
---
apiVersion: v1
kind: Service
metadata:
  name: greycat
  namespace: wattopus
spec:
  selector: { app: greycat }
  type: NodePort
  ports: [{ port: 8080, nodePort: 30808 }]
