
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubediagram
  namespace: wattopus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubediagram
  namespace: wattopus
rules:
  - apiGroups: [""]
    resources: [pods, services, configmaps, serviceaccounts]
    verbs: [get, list]
  - apiGroups: [apps]
    resources: [deployments, replicasets]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubediagram
  namespace: wattopus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubediagram
subjects:
  - kind: ServiceAccount
    name: kubediagram
    namespace: wattopus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubediagram
  namespace: wattopus
  labels: { app: kubediagram }
spec:
  replicas: 1
  selector:
    matchLabels: { app: kubediagram }
  template:
    metadata:
      labels: { app: kubediagram }
    spec:
      serviceAccountName: kubediagram
      containers:
        - name: kubediagram
          image: inkedstinct/kubediagram:0.1
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8000 }]
          env:
            - { name: NAMESPACE, value: wattopus }
            - { name: INTERVAL, value: "10" }
---
apiVersion: v1
kind: Service
metadata:
  name: kubediagram
  namespace: wattopus
spec:
  selector: { app: kubediagram }
  ports: [{ port: 8000 }]
